var cifrado =`[
 {"letra": "A", "numero": 12},
 {"letra": "B", "numero": 15},
 {"letra": "C", "numero": 21},
 {"letra": "D", "numero": 32},
 {"letra": "E", "numero": 45},
 {"letra": "F", "numero": 90},
 {"letra": "G", "numero": 87},
 {"letra": "H", "numero": 17},
 {"letra": "I", "numero": 55},
 {"letra": "J", "numero": 52},
 {"letra": "K", "numero": 99},
 {"letra": "L", "numero": 88},
 {"letra": "M", "numero": 77},
 {"letra": "N", "numero": 19},
 {"letra": "Ñ", "numero": 23},
 {"letra": "O", "numero": 47},
 {"letra": "P", "numero": 76},
 {"letra": "Q", "numero": 60},
 {"letra": "R", "numero": 61},
 {"letra": "S", "numero": 28},
 {"letra": "T", "numero": 44},
 {"letra": "U", "numero": 33},
 {"letra": "V", "numero": 35},
 {"letra": "W", "numero": 63},
 {"letra": "X", "numero": 66},
 {"letra": "Y", "numero": 70},
 {"letra": "Z", "numero": 84},
 {"letra": " ", "numero": 95},
 {"letra": ".", "numero": 62},
 {"letra": ",", "numero": 22},
 {"letra": ";", "numero": 11},
 {"letra": "¿", "numero": 10},
 {"letra": "?", "numero": 30},
 {"letra": ":", "numero": 87}
]`;